name: asis
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: .docker/start_web
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    tty: true
    volumes:
      - .:/app
      - bundler:/usr/local/bundle
    environment:
      MONGODB_URL: mongodb://mongodb:27017/toy_asis_development
      RAILS_ENV: development
      RACK_ENV: development

  mongodb:
    image: mongo:6-jammy
    ports:
      - 27017:27017
    volumes:
      - db-data:/data/db

volumes:
  db-data:
  bundler:
